---
- name: Ensuring config directories exist
  file:
    path: "{{ custom_config_dir }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "cord_profile"
    - "key"
    - "maven"

- name: Copying over config files for xos services
  template:
    src: "{{ item }}.j2"
    dest: "{{ config_directory }}/{{ item}}"
  with_items:
    - "docker-compose.yml"
    - "xos_config.yaml"
    
    
