- name: Create docker networks
  docker_network:
    name: "{{ item }}"
    ipam_options:
      subnet: '172.25.0.1/24'
  with_items: "{{ xos_docker_networks }}"
   



- name: Print cord_profile vars
  debug:
    var: "{{ cord_profile | regex_replace('\\W','') }}"

- name: Print cord_profile vars
  debug:
    var: "config_cord_profile_dir"

- name: Bring up XOS services
  docker_service:
    project_name: "rcord"
    project_src: "{{ config_cord_profile_dir }}"
    pull: "{{ always_pull_xos_images | default('false') }}"
#    state: absent
  register: output
  

- name: Print vars
  debug:
    var: output
