- name: pull images
  docker_image:
    name: "{{ item }}"
  with_items:
    - "gliderlabs/consul-server:0.6"
    - "gliderlabs/registrator:v7"
    - "nginx:1.13"
    - "redis:3.2"
    - "node:7.9.0"
    - "sebp/elk:564"


- name: sync chameleon to xos
  become: yes
  shell: "cp -r {{ work_dir}}/component/chameleon {{ work_dir}}/orchestration/xos/containers/xos/tmp.chameleon"

- name: sync chameleon
  become: yes
  shell: "cp -r {{ work_dir}}/component/chameleon {{ work_dir}}/orchestration/xos/containers/chameleon/tmp.chameleon"

- name: Build an image and push it to a private repo
  docker_image:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    tag: "{{ build_docker_tag }}"
    dockerfile: "{{ item.dockerfile }}"
    force: True
  with_items: "{{ xos_images }}"

- name: Tag and push to docker registry
  docker_image:
    name: "{{ item.name }}:{{ build_docker_tag }}"
    repository: "{{ docker_registry }}/{{ push_namespace }}/{{ item.prject_name}}:{{ push_docker_tag }}"
    push: yes
  with_items: "{{ xos_images }}"
