---

# used in deployment.yaml.j2
head_cord_profile_dir: "/opt/cord_profile"

xos_tosca_config_templates:

xos_tosca_config_templates:

xos_new_tosca_config_templates:

credentials_dir: "/opt/key/credentials"
xos_admin_user: "xosadmin@opencord.org"
xos_admin_pass: "{{ lookup('password', credentials_dir ~ '/xosadmin@opencord.org chars=ascii_letters,digits') }}"
xos_admin_first: XOS
xos_admin_last: Admin
onos_ip: 10.10.10.7
local_management_ip: 10.1.1.7/24
xos_ip: 10.10.10.7

