- name: Include variables
  include_vars: "{{ item }}"
  with_items:
     - "../../../profiles/{{ cord_profile }}/{{ cord_scenario }}.yml"
     - "local_vars.yml"

- include: create-configdir.yml

- include: pki-roo-ca.yml

- include: pki-intermediate-ca.yml

- include: pki-cert.yml

- include: ssh-pki.yml

- include: cord_profile.yml 
