- name: Bootstrap XOS database - create site, deployment, admin user
  uri:
    url: "{{ xos_tosca_url }}/run"
    method: POST
    headers:
      xos-username: "{{ xos_admin_user }}"
      xos-password: "{{ xos_admin_pass }}"
    body: "{{ lookup('file', head_cord_profile_dir + '/' + item ) }}"
    status_code: 200
  register: result
  until: result | success
  retries: 50
  delay: 5
  with_items:
    - "fixtures.yaml"
    - "deployment.yaml"

- name: Configure XOS with OpenStack config
  uri:
    url: "{{ xos_tosca_url }}/run"
    method: POST
    headers:
      xos-username: "{{ xos_admin_user }}"
      xos-password: "{{ xos_admin_pass }}"
    body: "{{ lookup('file', head_cord_profile_dir + '/' + item ) }}"
    status_code: 200
  register: result
  until: result | success
  retries: 50
  delay: 5
  with_items:
    - openstack.yaml
