#- name: Apply role genconfig
#  gather_facts: false
#  hosts:
#    - localhost
#  serial: '{{ serial|default("0") }}'
#  roles:
#    - { role: genconfig,
#        tags: genconfig }

- name: Gather facts for all hosts
  hosts: all
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  tasks:
    - setup:
  tags: always


- name: Apply role cord_profile
  gather_facts: false
  hosts:
    - localhost
  roles:
    - { role: cord_profile,
        tags: cord_profile }

- name: Apply role xos
  gather_facts: false
  hosts:
    - xos
  roles:
    - { role: xos,
        tags: xos }

- name: Apply role onos
  gather_facts: false
  hosts:
    - onos-cord
    - onos-fabric
  serial: '{{ serial|default("0") }}'
  roles:
    - { role: onos,
        tags: onos }

